// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Superelf.Infrastructure.Data;

#nullable disable

namespace Superelf.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807174221_AddedLineUpSpecificLocation")]
    partial class AddedLineUpSpecificLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440000",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440001",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440002",
                            RoleId = "550e8400-e29b-41d4-a716-446655440000"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Superelf.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b69a9d2a-3221-4764-b281-33d36a70f9af",
                            Email = "admin@superelf.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SUPERELF.COM",
                            NormalizedUserName = "ADMIN@SUPERELF.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBAnLgiWswkLSrmSz6GBPMoOJ2wDnhl1A9PM+kvSMNwnzOcRIoFvc3jWxE0cuC96g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "36d1ff68-e7cb-48d6-bbec-6096a55c70ba",
                            TwoFactorEnabled = false,
                            UserName = "admin@superelf.com"
                        });
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MigrationTestColumn")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6681),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Ajax",
                            ShortName = "AJX"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6695),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "PSV",
                            ShortName = "PSV"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6821),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Feyenoord",
                            ShortName = "FEY"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6834),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "AZ",
                            ShortName = "AZ"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6846),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "FC Utrecht",
                            ShortName = "UTR"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6868),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "FC Twente",
                            ShortName = "TWE"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6880),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Vitesse",
                            ShortName = "VIT"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6893),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "SC Heerenveen",
                            ShortName = "HEE"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6904),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "FC Groningen",
                            ShortName = "GRO"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6917),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Willem II",
                            ShortName = "WIL"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6929),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "NEC",
                            ShortName = "NEC"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6940),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Fortuna Sittard",
                            ShortName = "FOR"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6951),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Go Ahead Eagles",
                            ShortName = "GAE"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6962),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Heracles Almelo",
                            ShortName = "HER"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6973),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "PEC Zwolle",
                            ShortName = "PEC"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6984),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "RKC Waalwijk",
                            ShortName = "RKC"
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6995),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Sparta Rotterdam",
                            ShortName = "SPA"
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(7008),
                            LeagueId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Almere City",
                            ShortName = "ALM"
                        });
                });

            modelBuilder.Entity("Superelf.Domain.Entities.FootballPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Club")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("FootballPlayers");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleCalendarId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2025, 8, 7, 17, 42, 21, 154, DateTimeKind.Utc).AddTicks(6629),
                            IsActive = true,
                            Name = "Eredivisie",
                            ShortName = "ERE"
                        });
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Lineup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PoolUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoolUserId");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.LineupLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FootballPlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsJoker")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReserve")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LineupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecificPosition")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FootballPlayerId");

                    b.HasIndex("LineupId");

                    b.ToTable("LineupLines");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Competition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasColumnType("text");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.PlayerPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnGoals")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltiesMissed")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyGoals")
                        .HasColumnType("integer");

                    b.Property<bool>("Played")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerPerformances");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.PoolParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PoolId");

                    b.ToTable("PoolParticipants");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.UserScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasUsedJoker")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("UserId");

                    b.ToTable("UserScores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Club", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.FootballPlayer", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.Club", "ClubEntity")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClubEntity");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Lineup", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.PoolParticipant", "PoolUser")
                        .WithMany()
                        .HasForeignKey("PoolUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoolUser");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.LineupLine", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.FootballPlayer", "FootballPlayer")
                        .WithMany()
                        .HasForeignKey("FootballPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Superelf.Domain.Entities.Lineup", "Lineup")
                        .WithMany("LineupLines")
                        .HasForeignKey("LineupId");

                    b.Navigation("FootballPlayer");

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Match", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.PlayerPerformance", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.Match", "Match")
                        .WithMany("PlayerPerformances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Superelf.Domain.Entities.FootballPlayer", "Player")
                        .WithMany("Performances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Pool", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.PoolParticipant", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Superelf.Domain.Entities.Pool", "Pool")
                        .WithMany("Participants")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.UserScore", b =>
                {
                    b.HasOne("Superelf.Domain.Entities.Pool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Superelf.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.FootballPlayer", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.League", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Lineup", b =>
                {
                    b.Navigation("LineupLines");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Match", b =>
                {
                    b.Navigation("PlayerPerformances");
                });

            modelBuilder.Entity("Superelf.Domain.Entities.Pool", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
