FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY . .

COPY Superelf.API/appsettings*.json Superelf.API/


# Install EF Core tools
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
# Optionally list migration files for debugging
RUN find Superelf.Infrastructure/Migrations -type f -name "*.cs" | sort
